// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEuDonh282EfOyjTNUrZV2SLbmxViqtc',
    appId: '1:675855912277:web:f72617aaee5b7c993973dc',
    messagingSenderId: '675855912277',
    projectId: 'dlivry-b7373',
    authDomain: 'dlivry-b7373.firebaseapp.com',
    storageBucket: 'dlivry-b7373.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZp4fbU19BKn3UXAsBAXuBNRGAXp6paQ0',
    appId: '1:675855912277:android:eb5a8166df22b1e83973dc',
    messagingSenderId: '675855912277',
    projectId: 'dlivry-b7373',
    storageBucket: 'dlivry-b7373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApf8Go46r93p2bKa0B0XsQNTEwT-22jUM',
    appId: '1:675855912277:ios:74c7a12dbbd6aac33973dc',
    messagingSenderId: '675855912277',
    projectId: 'dlivry-b7373',
    storageBucket: 'dlivry-b7373.appspot.com',
    iosClientId: '675855912277-0ce8u21l6s5i5mdek9k4fcd3n3tift2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dlivry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApf8Go46r93p2bKa0B0XsQNTEwT-22jUM',
    appId: '1:675855912277:ios:74c7a12dbbd6aac33973dc',
    messagingSenderId: '675855912277',
    projectId: 'dlivry-b7373',
    storageBucket: 'dlivry-b7373.appspot.com',
    iosClientId: '675855912277-0ce8u21l6s5i5mdek9k4fcd3n3tift2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dlivry',
  );
}
